#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
kensho-value-feed — 既存kakaku価格データをGitHub README + FEED.mdへ「誠実に」自動拡散するMVPパイプライン。

実データのみを掲載（フィラー・捏造禁止）。各商品行に source(アクターリンク) と repo(GitHubリンク) を必須付与。
スクリプト単体 = データ収集→value-feed.json + FEED.md 生成。

使い方:
    python scripts/value_feed.py            # 生成のみ（コミットしない）
    python scripts/value_feed.py --commit   # 生成 + FEED.md / data/ を git commit + push
"""

from __future__ import annotations

import argparse
import asyncio
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import TypedDict

import httpx

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

# 固定キーワード（設計決定: iPhone に固定しデータ量で調整）
KEYWORDS = ["iPhone"]
TOP_N = 10

# 誠実拡散ロジック: 出典リンク（source = Apify actor / repo = GitHubリポジトリ）
ACTOR_ID = "fruitful_quintessence/japan-kakaku-price-search"
ACTOR_URL = f"https://apify.com/{ACTOR_ID}"
REPO_URL = "https://github.com/atushi1841/japan-kakaku-price-search"


class ValueFeed(TypedDict):
    """value-feed.json の各行スキーマ。"""

    keyword: str
    product: str
    lowest_price_yen: int
    shop_count: int
    review_score: float
    fetched_at: str
    source: str
    repo: str


def parse_review(raw: str | None) -> float | None:
    """'4.25 (44)' 形式のレビュー文字列からスコア(float)を抽出。無ければ None。"""
    if not raw:
        return None
    m = re.search(r"([0-9]+(?:\.[0-9]+)?)", raw)
    if m:
        try:
            return round(float(m.group(1)), 3)
        except ValueError:
            return None
    return None


async def collect(keyword: str, max_items: int = 40) -> list[ValueFeed]:
    """価格.comから実データを収集し、value-feed用スキーマへ整形する。"""
    from sources.kakaku import search_kakaku  # type: ignore[import-not-found]

    async with httpx.AsyncClient(timeout=30.0, follow_redirects=True) as client:
        raw = await search_kakaku(client, keyword=keyword, max_pages=2, max_items=max_items)

    # 最安価格 > 0 のみ採用（設計決定）
    valid: list[ValueFeed] = []
    for it in raw:
        price = it.get("price")
        try:
            price_int = int(price)
        except (TypeError, ValueError):
            continue
        if price_int <= 0:
            continue
        shop_count = int(it.get("shopCount", 0) or 0)
        review_score = parse_review(it.get("review", ""))
        fetched_at = str(it.get("scrapedAt", ""))
        if not fetched_at:
            fetched_at = datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")
        valid.append({
            "keyword": keyword,
            "product": it.get("title", "").strip(),
            "lowest_price_yen": price_int,
            "shop_count": shop_count,
            "review_score": review_score if review_score is not None else 0.0,
            "fetched_at": fetched_at,
            "source": ACTOR_URL,
            "repo": REPO_URL,
        })
    return valid


def select_top(items: list[ValueFeed], top_n: int = TOP_N) -> list[ValueFeed]:
    """価値選択ルール: review_score 降順 → 同点なら shop_count 降順。上位 top_n 件。"""
    scored = sorted(items, key=lambda x: (x["review_score"], x["shop_count"]), reverse=True)
    return scored[:top_n]


def build_markdown(rows: list[ValueFeed], generated_at: str) -> str:
    """FEED.md を構築。見出し+表+誠実フッター。"""
    lines: list[str] = []
    lines.append("# 日本市場・人気商品の最安価格フィード")
    lines.append("")
    lines.append("（価格.com から自動収集した横断価格データ — 出典: 価格.com / Apifyアクター）")
    lines.append("")
    lines.append("| 商品名 | 最安価格 (円) | ショップ数 | レビュー | 収集日 | 出典 |")
    lines.append("|---|---|---:|---:|---|---|")
    for r in rows:
        product = r["product"].replace("|", "\\\\|")
        price = f"{r['lowest_price_yen']:,}"
        shops = str(r["shop_count"])
        review = f"{r['review_score']:.2f}"
        fetched = r["fetched_at"][:10]
        lines.append(f"| {product} | {price} | {shops} | {review} | {fetched} | [kakaku]({r['source']}) |")
    lines.append("")
    # 誠実フッター: 実収集日(fetched_at)を明示。generated_atはUTCのため実収集日を優先
    refresh_date = rows[0]["fetched_at"][:10] if rows else generated_at[:10]
    lines.append(f"*Generated by kensho-value-feed · data refreshed {refresh_date}*")
    lines.append("")
    lines.append("---")
    lines.append(".値はすべて価格.com（[japan-kakaku-price-search](https://apify.com/"
                 "fruitful_quintessence/japan-kakaku-price-search)）が実収集したものです。")
    lines.append("")
    return "\n".join(lines)


def git(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], capture_output=True, text=True, cwd=str(REPO_ROOT))


def ensure_data_dir() -> Path:
    d = REPO_ROOT / "data"
    d.mkdir(parents=True, exist_ok=True)
    return d


def update_readme() -> bool:
    """README.md の末尾に FEED セクションを追加（既存ならスキップ）。"""
    readme = REPO_ROOT / "README.md"
    if not readme.exists():
        return False
    text = readme.read_text(encoding="utf-8")
    marker = "## 📈 最新価格フィード"
    if marker in text:
        return True
    feed_md = REPO_ROOT / "FEED.md"
    link = "[日本市場・人気商品の最安価格フィード](./FEED.md)"
    addition = (
        "\n---\n\n"
        "## 📈 最新価格フィード\n\n"
        f"{link}\n\n"
        "*このページは自動更新されます。詳細データは [FEED.md](./FEED.md) を参照。*\n"
    )
    readme.write_text(text + addition, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--commit", action="store_true", help="生成後に git commit + push する")
    args = parser.parse_args()

    now = datetime.datetime.now(datetime.timezone.utc)
    generated_at = now.isoformat().replace("+00:00", "Z")

    # 実データ収集
    collected_all: list[ValueFeed] = []
    for kw in KEYWORDS:
        collected_all.extend(asyncio.run(collect(kw)))

    if not collected_all:
        print("データ収集に失敗しました（価格.comからのレスポンスがありません）。", file=sys.stderr)
        return 2

    rows = select_top(collected_all)

    # JSON 生成
    data_dir = ensure_data_dir()
    json_path = data_dir / "value-feed.json"
    json_path.write_text(
        json.dumps(rows, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    # FEED.md 生成
    md_path = REPO_ROOT / "FEED.md"
    md_path.write_text(build_markdown(rows, generated_at), encoding="utf-8")

    # README 更新
    update_readme()

    print(f"value-feed.json 生成: {len(rows)} 件 -> {json_path.relative_to(REPO_ROOT)}")
    print(f"FEED.md 生成: {md_path.relative_to(REPO_ROOT)}")
    print(f"生成時刻: {generated_at}")

    # コミット
    if args.commit:
        for f in ["data/value-feed.json", "FEED.md", "README.md", "scripts/value_feed.py"]:
            if (REPO_ROOT / f).exists():
                git(["add", f])
        diff = git(["diff", "--cached", "--stat"]).stdout.strip()
        if diff:
            commit_msg = f"kensho-value-feed: {len(rows)}件の実価格データを更新 (auto)"
            git(["commit", "-m", commit_msg])
            push = git(["push"])
            if push.returncode != 0:
                print(f"push失敗: {push.stderr}", file=sys.stderr)
                return 3
            print("commit + push 完了")
        else:
            print("変更なし（コミット・プッシュ対象なし）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
